version: '3.8'

services:
  db:
    image: postgres:17
    container_name: demo_postgres
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"